### ISSUE TITLE
Don't set passwords to `passwords`

### ISSUE THREAD

**Issue by jdlrobson** [rmoen/Barry-the-Browser-Test-Bot-Installer#1]
Use the unix password given by the user in the prompt for more security. Remember this could be a publicly accessible url!

**Comment by rmoen** [comment]
Will have to prompt for additional password.  The password entered when creating the user is handled by the adduser command.

**Comment by rmoen** [comment]
21334cbe97f8e018304a0b45e86cb3932029799b
