### ISSUE TITLE
Selenium user should be a sysop and a bureaucrat

### ISSUE THREAD

**Issue by jdlrobson** [rmoen/Barry-the-Browser-Test-Bot-Installer#5]
Various tests require advanced privileges such as ability to protect pages
Luckily this can be automated by running

> php maintenance/createAndPromote.php "Mr Selenium" --bureaucrat --force --sysop

**Comment by rmoen** [comment]
2a69d2a8cdceaeffad7962e6e3185f71a28466fb and 197b9a5596d6a6d3e4a021572d846ac1dc08951a

**Comment by rmoen** [comment]
197b9a5596d6a6d3e4a021572d846ac1dc08951a
