### ISSUE TITLE
Setup interwiki language links

### ISSUE THREAD

**Issue by jdlrobson** [rmoen/Barry-the-Browser-Test-Bot-Installer#8]
This can be down by running the mysql command:

> INSERT INTO wiki.interwiki (iw_prefix, iw_url, iw_local, iw_trans) VALUES ("es", "http://wikifoo.org/es/index.php/$1", 0, 0);

and running

> php maintenance/update.php

Note MobileFrontend requires this and there is no harm setting it up for other projects.
To be generic would be great to have an sql file where we can add further queries later;

**Comment by rmoen** [comment]
c1e92a83ba24cbf54c7d728f6e63752b115d2c67 introduces the interwiki.sql file, but bash is having issues finding it when running mysql command

**Comment by jdlrobson** [comment]
Whilst installing I got this:
./install.sh: 155: ./install.sh: cannot open interwiki.sql: No such file

Note after manually running it I had to vafrant provision again

**Comment by rmoen** [comment]
71cefbd88163fcbeac517394d92b9ed413da1dda
