### ISSUE TITLE
Created unix user should have permission to use git

### ISSUE THREAD

**Issue by jdlrobson** [rmoen/Barry-the-Browser-Test-Bot-Installer#9]
> sudo su barrythebrowsertestbot
> cd /vagrant/mediawiki/extensions/MobileFrontend/ && git stash && git checkout master && git review -d 226446
> No local changes to save
> fatal: Unable to create '/vagrant/mediawiki/extensions/MobileFrontend/.git/index.lock': Permission denied

**Comment by jdlrobson** [comment]
Running

> sudo chmod a+rw /vagrant/mediawiki -R

fixed this.

I was prompted for my Gerrit username but I believe that is because I setup my unix username differently from the gerrit username :)

**Comment by rmoen** [comment]
Fixed in a13c5402766f4f0d94d60061558d2dfa806b3059 by adding user to wikidev group
